"""test running migrations

Revision ID: 77b0a4d30d6d
Revises: 54d8094ef2bf
Create Date: 2023-09-06 16:35:03.256198

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "77b0a4d30d6d"
down_revision: Union[str, None] = "54d8094ef2bf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
