"""test running migrations

Revision ID: 7a459d1e8a8d
Revises: 77b0a4d30d6d
Create Date: 2023-09-06 16:35:24.313630

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "7a459d1e8a8d"
down_revision: Union[str, None] = "77b0a4d30d6d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
